name: Ifrat_Unitest

on:
  push:
    branches:
      - Ifrat_Unittest
  pull_request:
    branches:
      - Ifrat_Unittest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build  # Add this if your project requires a build step

      - name: Verify Expo CLI
        run: npx expo --version

      - name: Run unit tests
        run: yarn test --ci --silent

      - name: Start Expo server
        run: npx expo start --non-interactive --dev --no-minify
